GMAIL_USERNAME: example@my.bristol.ac.uk
GMAIL_PASSWORD: passwordExample
MAILCHIMP_API_KEY: 1b9769effd2d4ec3fb494384da2d8b07-us3
MAILCHIMP_LIST_ID: 5b5c096269
DOMAIN_NAME: chaser.com
OWNER_EMAIL: rootnash@gmail.com
